### ISSUE TITLE
我觉得贵项目对错误的处理非常不负责、、

### ISSUE THREAD

**Issue by mrs-joker** [PandaXGO/PandaX#2]
我觉得贵项目对错误的处理非常不负责、、遇到错误直接pannic。。整个程序退出、、奇奇怪怪！

**Comment by PandaX-Go** [comment]
接口响应楚做了异常捕获

**Comment by mrs-joker** [comment]
接口里新起了子协程，子协程 pannic ....就完犊子了啊、、
PandaX\apps\develop\gen\gen.go里的  接口方法  GenConfigure

**Comment by PandaX-Go** [comment]
go语言中被诟病的主要就是error，因此框架做了处理，子协程在进行error捕获，要不然每次都要处理error。

**Comment by mrs-joker** [comment]
你们的GO项目应该pannic挂了、、昨晚我这边测试的时弄的，有空重启下吧、、不好意思

**Comment by findgo** [comment]
要不是新司基于这个改的, 我都懒着说, 这错误处理极其不负责,号称企业级也不敢这么干. 又不是java处理错误. 显示处理错理本来就是趋势. 在go中panic,还要做调用栈回溯. 这性能降的猛的一批. 实在不懂处理, 国内基本框架参考kratos,go-zero. 语言层面看看rust处理方法.
